from __future__ import annotations
from typing import Optional
from pathlib import Path
from datetime import datetime

from schemas.schema import PredictionOutput, ProjectionSeries

try:
    from docx import Document
except Exception:  # pragma: no cover - optional dependency
    Document = None

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
except Exception:  # pragma: no cover - optional dependency
    Presentation = None


def prediction_to_markdown(pred: PredictionOutput) -> str:
    """Render a `PredictionOutput` as a human-readable Markdown report."""
    lines = []
    lines.append(f"# Prediction Report — {pred.ticker or 'UNKNOWN'}")
    lines.append("")
    lines.append(f"**Generated at:** {pred.generated_at.isoformat()}")
    lines.append("")

    # Valuation
    if pred.valuation:
        lines.append("## Valuation")
        lines.append(f"- DCF value: {pred.valuation.dcf_value}")
        lines.append(f"- Terminal value: {pred.valuation.terminal_value}")
        lines.append("- Assumptions:")
        for k, v in pred.valuation.assumptions.items():
            lines.append(f"  - {k}: {v}")
        lines.append("")

    # Projections
    if pred.projections:
        lines.append("## Projections")
        for ps in pred.projections:
            lines.append(f"### {ps.name} ({ps.unit or ''} {ps.currency or ''})")
            lines.append("")
            lines.append("| Period | Value | Growth |")
            lines.append("|---:|---:|---:|")
            for e in ps.entries:
                gr = e.growth_rate if e.growth_rate is not None else ""
                lines.append(f"| {e.period} | {e.value} | {gr} |")
            lines.append("")

    # Evidence
    if pred.evidence:
        lines.append("## Evidence")
        for ev in pred.evidence:
            lines.append(f"- **{ev.source}**: {ev.description} {(' (conf='+str(ev.confidence)+')') if ev.confidence is not None else ''}")
        lines.append("")

    # Trace
    if pred.trace:
        lines.append("## Execution Trace")
        for t in pred.trace:
            lines.append(f"- {t.step} @ {t.timestamp} ({t.duration_ms or 'n/a'} ms)")
        lines.append("")

    lines.append("---")
    lines.append(f"Generated by Pitt Predictor on {datetime.utcnow().isoformat()}Z")
    return "\n".join(lines)


def export_prediction_report(pred: PredictionOutput, out_path: Path, fmt: str = "md") -> Path:
    """Export prediction to a report file.

    - `fmt` can be `md` (Markdown), `pdf`, `docx`, or `pptx`.
    - This function currently writes Markdown natively. For PDF/DOCX/PPTX it will
      write Markdown and return that path — user can convert with Pandoc or similar.
    """
    out_path = Path(out_path)
    md = prediction_to_markdown(pred)
    fmt = fmt.lower()
    if fmt == "md":
        out_path.write_text(md, encoding="utf-8")
        return out_path

    if fmt == "docx":
        if Document is None:
            raise RuntimeError("python-docx is not installed")
        doc = Document()
        doc.add_heading(f"Prediction Report — {pred.ticker or 'UNKNOWN'}", level=1)
        doc.add_paragraph(f"Generated at: {pred.generated_at.isoformat()}")

        if pred.valuation:
            doc.add_heading("Valuation", level=2)
            doc.add_paragraph(f"DCF value: {pred.valuation.dcf_value}")
            doc.add_paragraph(f"Terminal value: {pred.valuation.terminal_value}")

        if pred.projections:
            doc.add_heading("Projections", level=2)
            for ps in pred.projections:
                doc.add_heading(ps.name, level=3)
                table = doc.add_table(rows=1, cols=3)
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Period'
                hdr_cells[1].text = 'Value'
                hdr_cells[2].text = 'Growth'
                for e in ps.entries:
                    row_cells = table.add_row().cells
                    row_cells[0].text = str(e.period)
                    row_cells[1].text = str(e.value)
                    row_cells[2].text = str(e.growth_rate or '')

        if pred.evidence:
            doc.add_heading("Evidence", level=2)
            for ev in pred.evidence:
                doc.add_paragraph(f"{ev.source}: {ev.description} ({ev.confidence if ev.confidence is not None else ''})")

        out_file = out_path.with_suffix('.docx')
        doc.save(out_file)
        return out_file

    if fmt == "pptx":
        if Presentation is None:
            raise RuntimeError("python-pptx is not installed")
        prs = Presentation()
        # Title slide
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"Prediction Report — {pred.ticker or 'UNKNOWN'}"
        subtitle.text = f"Generated at: {pred.generated_at.isoformat()}"

        # Valuation slide
        if pred.valuation:
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            title = slide.shapes.title
            title.text = 'Valuation'
            body = slide.shapes.placeholders[1].text_frame
            body.text = f"DCF value: {pred.valuation.dcf_value}"
            p = body.add_paragraph()
            p.text = f"Terminal value: {pred.valuation.terminal_value}"

        # Projection slides (one per series)
        for ps in pred.projections:
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            title = slide.shapes.title
            title.text = ps.name
            body = slide.shapes.placeholders[1].text_frame
            for e in ps.entries:
                p = body.add_paragraph()
                p.text = f"{e.period}: {e.value} (growth: {e.growth_rate or ''})"

        out_file = out_path.with_suffix('.pptx')
        prs.save(out_file)
        return out_file

    # Default: write markdown intermediate
    md_path = out_path.with_suffix('.md')
    md_path.write_text(md, encoding="utf-8")

    if fmt == "pdf":
        # Attempt to run pandoc to convert markdown -> pdf
        try:
            import shutil
            from subprocess import check_call
        except Exception:
            raise RuntimeError("Pandoc conversion requires Python subprocess support")

        pandoc = shutil.which("pandoc")
        if not pandoc:
            raise RuntimeError("Pandoc is not installed or not on PATH. Install pandoc to enable PDF conversion.")

        out_pdf = out_path.with_suffix('.pdf')
        # Use xelatex when available for better font handling; pandoc falls back if not
        try:
            check_call([pandoc, str(md_path), "-o", str(out_pdf), "--pdf-engine=xelatex"])
        except Exception as exc:
            raise RuntimeError(f"Pandoc failed to convert markdown to PDF: {exc}")
        return out_pdf

    return md_path
